name: Run Test in every PR

on:
  pull_request:
    branches:
        - main        

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Compose
      run: |
        docker compose build --no-cache
        docker compose up --abort-on-container-exit --exit-code-from test_runner
